export const FAMILY_TIERS = {
  // Tier 1
  beast: 1,
  humanoid: 1,
  slimeborn: 1,
  plant: 1,
  dog: 1,
  thief: 1,
  miner: 1,
  archer: 1,
  warrior: 1,
  monk: 1,
  assassin: 1,
  bandit: 1,
  insectoid: 1,
  arachnid: 1,
  fae: 1,
  construct: 1,

  // Tier 2
  druid: 2,
  shaman: 2,
  witch: 2,
  necromancer: 2,
  warlock: 2,
  elemental: 2,
  spirit: 2,
  ranger: 2,
  ritualist: 2,
  chaosborn: 2,
  beast_elite: 2,
  humanoid_elite: 2,

  // Tier 3
  demon: 3,
  void: 3,
  celestial: 3,
  aberration: 3,
  eldritch: 3,
  arcane: 3,
  astral: 3,
  mythic_beast: 3,
  mythic_undead: 3,
  giantkin: 3,
  colossus: 3,

  // Tier 4
  astral_beast,
  titan: 4,
  nature_colossus: 4,
  thunder_colossus: 4,
  glacier_titan: 4,
  storm_titan: 4,
  world_titan: 4,
  obsidian_world_breaker: 4,
  tide_forged_leviathan: 4,

  // Tier 5
  primordial: 5,
  outer_god: 5,
  void_god: 5,
  anomaly: 5,
  hivemind: 5,
  metaphysical_phenomenon: 5,
  divinity: 5,
  paragon: 5,
  multiversal_paragon: 5,
  cosmic_crowned_terminarch: 5
};
