// region-biomes.js
// Canonical mapping from region key → biome key.

export const REGION_BIOMES = {
  "forest-edge": "forest",
  "deep-forest": "forest",
  "plains-field": "plains",
  "swamp-marsh": "swamp",
  "crystal-pass": "mountains",
  "cave-entrance": "cavern",
  "ruins-outskirts": "ruins",
  "desert-dunes": "desert",
  "highland-cliffs": "mountains",
  "volcano-rim": "volcanic",
  "tundra-wastes": "tundra",
  "mountain-peak": "mountains",
  "void-realm": "void",
  "astral-plane": "astral",
  "abyss-gate": "abyssal",
  "spirit-kingdom": "celestial",
  "outcast-island": "coastal",
  "trainers-city": "plains",
  "titanfall": "mountains",

  "verdant-woods": "forest",
  "frostlands": "tundra",
  "volcanic-wastes": "volcanic",
  "azure-coast": "coastal",
  "sunspire-highlands": "mountains",
  "void-spire": "void",
  "crystal-caverns": "cavern",
  "highlands-of-thorne": "mountains",
  "shattered-desert": "desert",
  "abyssal-scar": "abyssal",
  "arcane-riftlands": "arcane",
  "primordial-grove": "primeval",
  "celestial-expanse": "celestial",
  "eternal-citadel": "celestial",
  "worldbreaker-horizon": "void",
  "astral-nexus": "astral",
  "deep-caverns": "cavern",
  "ruined-kingdom": "ruins",
  "whispering-marsh": "swamp",
  "stormbreaker-coast": "storm",
  "emberforge-depths": "volcanic",
  "crystalline-tundra": "tundra",
  "abyssal-deep": "abyssal",

  "forest": "forest",
  "plains": "plains",
  "cavern": "cavern",
  "ruins": "ruins",
  "swamp": "swamp",
  "desert": "desert",
  "tundra": "tundra",
  "mountains": "mountains",

  "verdant-wildwood": "forest",
  "arcstone-enclave": "arcane",
  "emberfang-ridge": "volcanic",
  "void": "void",
  "celestial": "celestial",
  "arcane-rift": "arcane",
  "stormforge-sanctum": "storm",
  "molten-underdeep": "volcanic",
  "shadow-labyrinth": "void",
  "void-frontier": "void",
  "radiant-ascension-spire": "celestial",
  "seraphic-crucible": "celestial",
  "elderwood-heart": "primeval",
  "primeval-overgrowth": "primeval",
  "celestial-horizon": "celestial",
  "worlds-end-expanse": "void"
};
